export const FETCH_FILMS = 'FETCH_FILMS';
export const GET_FILM_DETAIL = 'GET_FILM_DETAIL';
export const SET_PAGE_LOCATION = 'SET_PAGE_LOCATION';
export const GET_BATCH_DETAILS = 'GET_BATCH_DETAILS';
export const LOADING_CONTENT = 'LOADING_CONTENT';
export const UNMOUNT_DATA = 'UNMOUNT_DATA';
export const UNMOUNT_FILM_DETAILS = 'UNMOUNT_FILM_DETAILS';